config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :citations, only: [:index, :show] do
    post 'review', on: :member
    patch 'review', on: :member
  end

  post 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'citations#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/abstract.rb
class Abstract < ApplicationRecord
  belongs_to :citation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citation.rb
class Citation < ApplicationRecord
  has_one :abstract
  has_many :reviews

  def status
    return 'included' if reviews.where(relevant: true).count >= 2

    return 'excluded' if reviews.where(relevant: false).count >= 2

    'undecided'
  end

  def review!(user, relevant)
    review = self.reviews.find_by(user: user)
    review ||= self.reviews.create(user: user, relevant: relevant)
    review
  end

  def reviewed?(user)
    self.reviews.exists?(user: user)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :citation

  validates :relevant, inclusion: [true, false]
end

app/models/user.rb
class User < ApplicationRecord
  validates_uniqueness_of :name, case_sensitive: false
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include ApplicationHelper

  def check_user
    redirect_to new_user_path if current_user.nil?
  end

end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController

  before_action :check_user

  def index
    # limit to first 20 since I'm also displaying the status
    @citations = Citation.all.limit(20)
  end

  def show
    @citation = Citation.find(params[:id])
  end

  def review
    @citation = Citation.find(params[:id])
    @citation.review!(current_user, params[:commit] == 'Relevant')
    redirect_to citations_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    # limit to first 20 since I'm also displaying the status
    clear_current_user
    redirect_to new_user_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    params.permit(:name)
    user = User.find_or_create_by(name: params[:user][:name])
    set_current_user(user)
    redirect_to citations_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    user_id = session[:current_user]
    User.find(user_id) unless user_id.nil?
  end

  def clear_current_user
    session[:current_user] = nil
  end

  def set_current_user(user)
    session[:current_user] = user.id
  end

end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/citations/_citation.html.erb
<tr>
  <td><%= link_to 'Review', citation_path(citation) %></td>
  <td><%= citation.title %></td>
  <td><%= citation.published_year %></td>
  <td><%= citation.status %></td>
</tr>

app/views/citations/index.html.erb
<h1>Citations</h1>

<table>
  <thead>
    <th></th>
    <th>Title</th>
    <th>Publised Date</th>
    <th>Status</th>
  </thead>
  <tbody>
    <%= render partial: 'citation', collection: @citations %>
  </tbody>
</table>

app/views/citations/show.html.erb
<h1><%= @citation.title %></h1>

<dl>
  <li><%= %></li>
</dl>

<dl>
  <dt>Authors</dt>
  <dd><%= @citation.authors %></dd>
  <dt>Published Year</dt>
  <dd><%= @citation.published_year %></dd>
  <dt>Pages</dt>
  <dd><%= @citation.pages %></dd>
  <dt>Journal</dt>
  <dd><%= @citation.journal %></dd>
</dl>

<p><%= @citation.abstract.content %></p>

<% if @citation.reviews.any? %>
<table>
  <thead>
    <th>User</th>
    <th>Relevant</th>
    <th>Reviewed On</th>
  </thead>
  <tbody>
    <%= render partial: 'reviews/review', collection: @citation.reviews %>
  </tbody>
</table>
<% end %>

<% unless @citation.reviewed?(current_user) %>
  <%= form_for @citation, :url => { action: 'review' } do |f| %>
    <%= f.submit 'Relevant' %>
    <%= f.submit 'Not relevant' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SystemicReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div>
      <% unless current_user.nil? %>
        <%= button_to 'logout', controller: 'sessions', action: 'destroy' %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/reviews/_review.html.erb
<tr>
  <td><%= review.user.name %></td>
  <td><%= review.relevant %></td>
  <td><%= review.created_at %></td>
</tr>

app/views/users/new.html.erb
<h1>Create User<h1>

<%= form_for @user, :url => { action: 'create' } do |f| %>
  <label>Name</label>
  <%= f.text_field :name %>
  <%= f.submit 'Submit' %>
<% end %>